bot:
  appId: 102072130
  clientToken: Lj0PWZAMztCEwr0UGk2jiJsxyY0Ctvhx
  clientSecret: suswwzxutwv02AEM

server:
  port: 8210
spring:
  main:
    banner-mode: log
  application:
    name: @project.artifactId@